/**
 * Regenerates the Better Auth tables in `@orkide/db`.
 *
 * The Better Auth CLI still emits Relational Queries v1 (`relations()`), which Drizzle v1 removed.
 * This wrapper keeps the generated tables and strips that block; relations for every table are
 * declared once in `@orkide/db/relations`.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const output = path.resolve(import.meta.dirname, "../../db/src/schema/auth.ts");
const config = path.resolve(import.meta.dirname, "../auth.cli.ts");
const run = (command: string, args: string[]) =>
  execFileSync(command, args, { stdio: "inherit" });

run("auth", ["generate", "--config", config, "--output", output, "--yes"]);

const generated = readFileSync(output, "utf-8");
const relationsStart = generated.search(
  /^export const \w+Relations = relations\(/mu
);
const tables =
  relationsStart === -1 ? generated : generated.slice(0, relationsStart);

writeFileSync(
  output,
  [
    "// Generated by `pnpm --filter @orkide/auth auth:generate` — do not edit by hand.",
    tables.replace(
      /import \{ relations, (?<imports>.+) \} from "drizzle-orm";/u,
      'import { $<imports> } from "drizzle-orm";'
    ),
  ].join("\n")
);

run("oxfmt", [output]);
